// 模擬數據
export interface MockRedPacket {
  id: string
  senderName: string
  senderAvatar: string
  senderLevel: number
  message: string
  totalQuantity: number
  remainingQuantity: number
  type: 'ordinary' | 'lucky' | 'exclusive'
  status: 'active' | 'completed' | 'expired'
  timestamp: number
  currency: 'USDT' | 'TON' | 'Stars'
  amount: number
  chatTitle?: string // 群組名稱（如果是從群組來的）
  isFromGameGroup?: boolean // 是否來自遊戲群
}

export const MOCK_RED_PACKETS: MockRedPacket[] = [
  {
    id: '1',
    senderName: 'dxw666',
    senderAvatar: 'https://picsum.photos/seed/dxw666/200',
    senderLevel: 1,
    message: 'Have fun! 🎉',
    totalQuantity: 100,
    remainingQuantity: 66,
    type: 'ordinary',
    status: 'active',
    timestamp: Date.now(),
    currency: 'USDT',
    amount: 100,
  },
  {
    id: '2',
    senderName: 'CryptoKing',
    senderAvatar: 'https://picsum.photos/seed/crypto/200',
    senderLevel: 55,
    message: 'To the moon! 🚀 Big rewards inside.',
    totalQuantity: 50,
    remainingQuantity: 5,
    type: 'lucky',
    status: 'active',
    timestamp: Date.now() - 100000,
    currency: 'USDT',
    amount: 500,
  },
  {
    id: '3',
    senderName: 'AliceWonder',
    senderAvatar: 'https://picsum.photos/seed/alice/200',
    senderLevel: 12,
    message: 'Weekend vibes only.',
    totalQuantity: 200,
    remainingQuantity: 0,
    type: 'ordinary',
    status: 'completed',
    timestamp: Date.now() - 500000,
    currency: 'USDT',
    amount: 200,
  },
  {
    id: '4',
    senderName: 'ElonMuskrat',
    senderAvatar: 'https://picsum.photos/seed/elon/200',
    senderLevel: 99,
    message: 'Just a small gift for the community.',
    totalQuantity: 10,
    remainingQuantity: 1,
    type: 'exclusive',
    status: 'active',
    timestamp: Date.now() - 20000,
    currency: 'USDT',
    amount: 1000,
  },
  {
    id: '5',
    senderName: 'DesignGuru',
    senderAvatar: 'https://picsum.photos/seed/guru/200',
    senderLevel: 24,
    message: 'Grab it before it disappears!',
    totalQuantity: 500,
    remainingQuantity: 450,
    type: 'ordinary',
    status: 'active',
    timestamp: Date.now() - 1000,
    currency: 'USDT',
    amount: 50,
  },
  // 遊戲群紅包
  {
    id: '6',
    senderName: 'GameMaster',
    senderAvatar: 'https://picsum.photos/seed/game1/200',
    senderLevel: 88,
    message: '🎮 遊戲群專屬紅包！',
    totalQuantity: 200,
    remainingQuantity: 120,
    type: 'lucky',
    status: 'active',
    timestamp: Date.now() - 5000,
    currency: 'USDT',
    amount: 300,
    chatTitle: '🎮 金福寶局遊戲群',
    isFromGameGroup: true,
  },
  {
    id: '7',
    senderName: 'LuckyPlayer',
    senderAvatar: 'https://picsum.photos/seed/game2/200',
    senderLevel: 45,
    message: '遊戲獲勝慶祝紅包！',
    totalQuantity: 80,
    remainingQuantity: 35,
    type: 'exclusive',
    status: 'active',
    timestamp: Date.now() - 3000,
    currency: 'USDT',
    amount: 150,
    chatTitle: '🎰 幸運遊戲大廳',
    isFromGameGroup: true,
  },
  {
    id: '8',
    senderName: 'Winner2025',
    senderAvatar: 'https://picsum.photos/seed/game3/200',
    senderLevel: 66,
    message: '連勝獎勵分享！',
    totalQuantity: 150,
    remainingQuantity: 90,
    type: 'lucky',
    status: 'active',
    timestamp: Date.now() - 8000,
    currency: 'USDT',
    amount: 250,
    chatTitle: '🏆 競技遊戲聯盟',
    isFromGameGroup: true,
  },
  {
    id: '9',
    senderName: 'ProGamer',
    senderAvatar: 'https://picsum.photos/seed/game4/200',
    senderLevel: 77,
    message: '每日任務完成獎勵',
    totalQuantity: 300,
    remainingQuantity: 200,
    type: 'ordinary',
    status: 'active',
    timestamp: Date.now() - 12000,
    currency: 'USDT',
    amount: 100,
    chatTitle: '🎯 專業玩家俱樂部',
    isFromGameGroup: true,
  },
  {
    id: '10',
    senderName: 'GameAdmin',
    senderAvatar: 'https://picsum.photos/seed/game5/200',
    senderLevel: 100,
    message: '官方活動紅包，快來搶！',
    totalQuantity: 500,
    remainingQuantity: 350,
    type: 'exclusive',
    status: 'active',
    timestamp: Date.now() - 15000,
    currency: 'USDT',
    amount: 500,
    chatTitle: '🎪 官方遊戲活動群',
    isFromGameGroup: true,
  },
]

